name: Build Proto Files
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "proto/**"
  pull_request:
    paths:
      - "proto/**"
      - ".github/workflows/build-proto.yml"

jobs:
  compile_proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - uses: trinsic-id/protoc-gen-sdk@main
        id: buildsdkwrappers
        with:
          protoPath: ${{github.workspace}}/proto
          swiftPath: ${{github.workspace}}/Sources/Trinsic
      - name: Compile proto files
        run: ./generate.bash
        shell: bash

      - uses: stefanzweifel/git-auto-commit-action@v4
