name: Update SDK Submodule (swift)

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/update-sdk.yml"

jobs:
  update_sdk_submodule:
    name: Update SDK Submodule
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'trinsic-id/sdk'
          ref: 'main'
          submodules: recursive
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v2
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Update the submodule
        run: |
          git checkout -b "update-sdk-swift"
          git submodule update --remote
          git add .
          git commit -m "Updated SDK Swift Submodule"
          git push --force --set-upstream origin "update-sdk-swift"
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh pr create --base main --title "Update SDK Swift Submodule" --body "Update SDK Swift Submodule"
